[package]
name = "flash"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
notify = "8.0.0"
tokio = { version = "1.45.1", features = ["full"] }
clap = { version = "4.5.40", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
